# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_obSj2eAPpc3bHAGnereweYNX5Ax56an
"""

import pandas as pd
from sklearn.cluster import KMeans

df = pd.read_csv("/content/nba_players_35_years_stats_and_bio.csv")

df

df['Player'] = df['PLAYER_NAME'] + ' ' + df['Season']

df['AGE'] = df['AGE_x']

df_final = df[['Player', 'AGE', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M',\
   'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST',\
   'STL', 'BLK', 'PF', 'PTS']]

df_final = df_final.dropna()

df_final = df_final.set_index("Player")

df_final

from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

# נניח שכבר הגדרת את 'Player' בתור האינדקס וביצעת נרמול (Scaling)
scaler = StandardScaler()
df_scaled = scaler.fit_transform(df_final)

def get_top_5_similar_players(player_name, df, scaled_data):
    # 1. נוודא שהשחקן אכן קיים בנתונים כדי למנוע שגיאות
    if player_name not in df.index:
        return "שחקן לא נמצא במסד הנתונים."

    # 2. מציאת האינדקס (מספר השורה) של השחקן המבוקש
    player_idx = df.index.get_loc(player_name)

    # שליפת וקטור הנתונים המנורמלים של השחקן
    player_vector = scaled_data[player_idx].reshape(1, -1)

    # 3. חישוב דמיון הקוסינוס בין השחקן לכל שאר השחקנים במסד הנתונים
    # מחזיר מערך של ציונים בין 1- ל-1
    similarities = cosine_similarity(player_vector, scaled_data).flatten()

    # 4. מציאת האינדקסים של השחקנים עם הציון הגבוה ביותר
    # argsort מסדר מהנמוך לגבוה, אז ניקח את ה-6 האחרונים ונהפוך את הסדר
    # (לוקחים 6 כי הראשון תמיד יהיה השחקן עצמו עם ציון של 1.0)
    top_indices = similarities.argsort()[-6:][::-1][1:]

    # 5. ארגון התוצאות לתוך טבלה מסודרת
    results = []
    for idx in top_indices:
        match_name = df.index[idx]
        score = similarities[idx]
        results.append({'Player': match_name, 'Similarity Score': round(score, 4)})

    return pd.DataFrame(results)

